CREATE TABLE drivers_orient (
class text,
fieldtypes text,
rid text,
type text,
version text,
active text,
created_at text,
deviceid text,
email text,
firstname text,
identity text,
in_has_owner text,
lastname text,
latitude text,
longitude text,
medical_weight text,
out_has_address text,
out_owned_by text,
out_user_role text,
password text,
phone text,
remember_token text,
standard text,
standard_weight text,
updated_at text,
work text
);

CREATE TABLE addresses_orient (
class text,
fieldtypes text,
rid text,
type text,
version text,
administrativearealevel1 text,
administrativearealevel2 text,
country text,
formattedaddress text,
in_drive_from text,
in_drive_to text,
in_has_address text,
latitude text,
locality text,
longitude text,
place_id text,
postalcode text,
route text,
slug text,
streetnumber text
);

CREATE TABLE drives_orient (
class text,
fieldtypes text,
rid text,
type text,
version text,
active text,
comment text,
created_at text,
deviceid text,
distanceoverride text,
email text,
firstname text,
identity text,
in_has_drive text,
in_has_owner text,
lastname text,
latitude text,
longitude text,
medical_weight text,
name text,
out_drive_from text,
out_drive_to text,
out_has_address text,
out_has_fare text,
out_owned_by text,
out_user_role text,
password text,
phone text,
remember_token text,
standard text,
standard_weight text,
twoway text,
type2 text,
updated_at text,
work text
);

CREATE TABLE fares_orient (
class text,
fieldtypes text,
rid text,
type text,
version text,
created_at text,
creator text,
date text,
distance text,
duration text,
in_has_entry text,
in_has_fare text,
isreturn text,
locked text,
meters text,
out_has_invoice text,
recurrent text,
status text,
subcontractor text,
time text,
timestamp text,
updated_at text,
weeklyrecurrence text
);

CREATE TABLE plannings_orient (
class text,
fieldtypes text,
rid text,
type text,
version text,
autoaffectendtime text,
autoaffectstarttime text,
created_at text,
deltabetweenentry text,
hasmedicallicense text,
out_has_entry text,
out_has_metric text,
out_has_owner text,
updated_at text
);

CREATE TABLE users_orient (
class text,
fieldtypes text,
rid text,
type text,
version text,
active text,
comment text,
created_at text,
deviceid text,
email text,
firstname text,
identity text,
lastname text,
latitude text,
longitude text,
name text,
out_has_address text,
out_has_drive text,
out_owned_by text,
out_user_role text,
password text,
phone text,
planning text,
remember_token text,
roles text,
socialnumber text,
status text,
super_user text,
updated_at text
);