name: Dispatch - Génère BDD à partir du dump sur scalingo

on:
  # Every night around 1AM
  #  schedule:
  #    - cron: "58 0 * * *"

  workflow_dispatch:

jobs:
  generate-db:
    uses: ./.github/workflows/postgres-from-orient.yml
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
      DUMP_FILENAME: ${{ secrets.DUMP_FILENAME }}
      ORIENTDB_DBLOGIN: ${{ secrets.ORIENTDB_DBLOGIN }}
      ORIENTDB_DBNAME: ${{ secrets.ORIENTDB_DBNAME }}
      ORIENTDB_DBPASSWORD: ${{ secrets.ORIENTDB_DBPASSWORD }}
      SSH_ZORA_LOGIN: ${{ secrets.SSH_ZORA_LOGIN }}
      SSH_ZORA_PASSWORD: ${{ secrets.SSH_ZORA_PASSWORD }}
      ZORA_USER: ${{ secrets.ZORA_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
      FINGERPRINT: ${{ secrets.FINGERPRINT }}


  notify-discord:
    needs:
      - generate-db
    runs-on: ubuntu-latest
    steps:
      - name: 'Do nothing'
        run: echo 'PLOP'
#      - name: Prepare payload
#        run: >-
#          (jq -r '.' <<< '
#          {
#            "username": "Taxibot",
#            "content": "Génération de la base effectuée avec succès"
#          }'
#          ) > payload
#
#      - name: Send notification
#        run: >-
#          curl
#          --header "Content-Type:application/json"
#          --request POST
#          --data @payload
#          ${{ secrets.DISCORD_NOTIFY_HOOK_URL }}